"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[kubernetes]
disabled = false
detect_env_vars = ["STARSHIP_K8S"]

[battery]
disabled = true

[directory]
truncate_to_repo = false
